# SITE SETUP
# Guide: https://docs.hugoblox.com/tutorial/
# Documentation: https://docs.hugoblox.com/
# This file is formatted using YAML syntax - learn more at https://learnxinyminutes.com/docs/yaml/

# Appearance

appearance:
  theme_day: minimal
  theme_night: minimal
  font: minimal
  font_size: L
  day_night: true

# SEO

marketing:
  seo:
    site_type: Person
    local_business_type: ''
    org_name: ''
    description: 'Ph.D. student at the University of Michigan, Ann Arbor'
    twitter: 'anleb1'
  analytics:
    google_analytics: '' # 'UA-228705789-1'
    baidu_tongji: ''
    google_tag_manager: ''
    microsoft_clarity: ''
  verification:
    google: '' #'google-site-verification=oJUt4qEgz1nbEKcvDXzsR0LNbHNPGcPECa2xegOaWp8'
    baidu: ''

# Site header

header:
  navbar:
    enable: true
    align: l
    show_logo: true
    show_language: false
    show_day_night: true
    show_search: true
    highlight_active_link: true

# Site footer

footer:
  block: minimal
  copyright:
    notice: '© {year} Andrej Leban. This work is licensed under {license}'
    license:
      enable: true
      allow_derivatives: false
      share_alike: true
      allow_commercial: false

# Localization

locale:
  date_format: 'Jan 2, 2006'
  time_format: '3:04 PM'
  address_format: en-us

# Site features

features:
#NOTE: see if this works
  highlight: true
  syntax_highlighter:
    highlight: true
    enable: true
    theme_light: github-light
    theme_dark: dracula
    #NOTE: see if this works
    highlight_languages:
      - r
      - python
      - latex
      - cpp
      - cmake
      - bash
  math:
    enable: true
  privacy_pack:
    enable: false
  repository:
    url: 'https://github.com/andleb/blog'
    content_dir: content
    branch: main
  show_related:
    book: true
    page: false
    post: true
    project: true
    publication: true
    event: true
  reading_time: true
  abstract_length: 135
  publications:
    date_format: January 2006
    citation_style: apa
  avatar:
    gravatar: false
    shape: circle
  comment:
    provider: ''
    disqus:
      shortname: ''
      show_count: true
    commento:
      url: ''
    giscus:
      repo: ''
      repo_id: ''
      category: ''
      category_id: ''
  search:
    provider: wowchemy
    algolia:
      app_id: ''
      api_key: ''
      index_name: ''
      show_logo: false
  map:
    provider: 'mapnik'
    api_key: ''
    zoom: 15

# Extensions

extensions:
  cms:
    branch: main
    local_backend: false
  academicons:
    enable: true

# Security

security:
  # Allow frame for embedding speaker notes in slides
  allow_frame: true
