---
title: "Diffusion models"
author: ''
date: '2022-10-02'
slug: diffusion-models
categories: []
tags:
  - Deep Learning
  - Statistics
  - Diffusion
subtitle: ''
summary: 'A brief introduction to diffusion models'
authors: []
lastmod: '2022-10-09T21:36:00-07:00'
featured: no
math: true
output:
  html_document:
    toc: true
    toc_depth: 2
image:
  caption: ''
  focal_point: ''
  preview_only: no
projects: []
draft: true
reading_time: true
share: true
---

{{% toc %}}
<!-- \tableofcontents -->

## Introduction

## Forward and reverse diffusion


### Forward

- 1-step update Kalman  

\begin{equation}
    q(x_t | x_{t-1}) = \mathcal{N}(\sqrt{1 - \beta_t}x_{t-1}, \beta_t \mathbf{I})
\end{equation}

Usually $\beta_1 < \beta_2 < ... < \beta_T$

#### Stochastic gradient Langevin


### Reverse

No closed form for $q(x_{t-1}|x_t)$ in general
Smoothing (needs the whole dataset) / Variational inference

But tractable $q(x_{t-1}|x_t, x_0)$

ELBO - sum of closed form terms


Train a NN to predict the mean

### Variance schedule

- simple linspace
- cosine based



## Conditional generation


## Examples

## Applications in GANs


## References

 - One of the earliest papers: [Sohl-Dickstein et al. - Deep Unsupervised Learning using Nonequilibrium Thermodynamics](https://arxiv.org/abs/1503.03585)  
 - A good blog post: [Weng, Lilian. (Jul 2021). What are diffusion models? Lil’Log.](https://lilianweng.github.io/posts/2021-07-11-diffusion-models/) 
 - [The Kalman filter](https://en.wikipedia.org/wiki/Kalman_filter)  
 - [My presentation on the Continuous-time Kalman filter](../../uploads/leban_andrej - continuous time kalman filter.pdf)  
 - [Blei, Kucukelbir, McAuliffe - Variational Inference: A Review for Statisticians](https://arxiv.org/abs/1601.00670)
 




